<?php 

 if (count($this->messages)) {?>
	<div id="dispmsgemp" class="settingssuccess">
		<?php 
			foreach ($this->messages as $message)
			{
				$flag = array();				
				$flag = array_keys($message);
				echo "<div id='messageData' class='ml-alert-1-$flag[0]'><div style='display:block;'><span class='style-1-icon $flag[0]'></span>";
				echo $message[$flag[0]];
				echo "</div></div>";
			} 
		?>
	</div>	
	
<?php }
if($this->ermsg !='')
		{
?>
     <div class="ml-alert-1-info m1-info-set"><div class="style-1-icon info"></div>No data found.</div>
<?php }else
{
 sapp_Global::generateClientValidations($this->form);
 $request = Zend_Controller_Front::getInstance();
 $actionName = $request->getRequest()->getActionName();
 	if($actionName == 'view')
 	  $viewclass = 'view-form-detail';
 	else
 	  $viewclass = '';  

 	 $departmentArr = array(); 
 	
 ?>
<div id="error_message" style="display:none;"></div>
<form name="<?php echo $this->form->getName(); ?>" id="<?php echo $this->form->getId(); ?>" action="<?php echo $this->form->getAction();?>" method="<?php echo $this->form->getMethod(); ?>">
		<?php echo $this->form->id; ?>
        <div class="total-form-controller <?php echo $viewclass;?>">
			<?php echo sapp_Helper::sd_form_helper($this->msgarray, $this->form, 'exit_type_id','', '','required',$departmentArr);?>
			<?php echo sapp_Helper::sd_form_helper($this->msgarray, $this->form, 'question',"Special characters allowed are - ? &#39; . , / # @ $ & * ( ) !", '','required',array());?>
			<?php echo sapp_Helper::sd_form_helper($this->msgarray, $this->form, 'description','', 'textareaheight','',array());?>
					
		<div class="new-form-ui-submit">
		<?php echo $this->form->submit; ?>
		<?php if($actionName == 'view'){?>
			<input type="button" onclick="changeeditscreen('<?php echo $this->controllername;?>',<?php echo $this->id;?>);" value="Edit" />
		<?php }?>
		<button onclick="window.location.href='<?php echo BASE_URL; ?>exit/configureexitqs';" type="button" id="Cancel" name="Cancel">Cancel</button>
		</div>
	</div>
</form>

	
<?php }?>