<?php 

?>
<?php
include("db_con.php");
?>
<?php if(empty($this->empdata)){?>
    <div class="ml-alert-1-info">
				<div class="style-1-icon info"></div>
				<?php if($this->rowexist == 'norows'){?>
					No data found.
				<?php }else{?>
						Employee inactivated.
				<?php }?>
	</div>
<?php
} else {
?>
<?php
$baseUrl = $this->serverUrl().$this->baseUrl();

if(!empty($this->employeedata))
 {
 	echo $this->employeedetails($this->employeedata,'edit',$this->id); 
 } 
?>

<div class="right-block-data right-over-border"> 
	<div id="error_message" style="display:none;"></div>
		<div class="ml-alert-1-info m1-info-set">
			<div class="mportformatlink flt_left"></div><a target="_blank" href="http://localhost/hrms/pdf.php?edit=<?php echo $this->id;?>" class="importformatlink flt_left">Download Payslip</a>
		</div>	
</div>	
</div>
<?php 
}
?>
<script type='text/javascript'>
$(document).ready(function(){
     /* Making window responsive*/
 	var complete_width = $('.poc-ui-data-control').width();
	$('.left-block-ui-data').css("width", "230");
	$('.right-block-data').css("width", (complete_width-(253)));	
		
	 function checkWidth() {
        var complete_width = $('.poc-ui-data-control').width();		
		$('.left-block-ui-data').css("width", "230");
		$('.right-block-data').css("width", (complete_width-(253)));		
    }
	$(window).resize(function() {
		checkWidth();
	}); 
    $("#emp_payslips").addClass('active');
    $("#emp_payslips").removeAttr("onclick");

});
</script>
